"use client";

import { useMemo, useState } from 'react';
import { 
  Search, 
  Filter, 
  Eye, 
  Wand2, 
  Clock,
  CheckCircle2,
  AlertCircle,
  Loader2,
  Download,
  MoreVertical,
  MessageSquare,
  ChevronRight,
  Package
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from '@/components/ui/table';
import { useFirestore, useCollection } from '@/firebase';
import { collection, query, orderBy, doc, updateDoc } from 'firebase/firestore';
import { cn } from '@/lib/utils';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import Image from 'next/image';
import { useToast } from '@/hooks/use-toast';

const STATUS_OPTIONS = [
  'Pending',
  'Reviewing Design',
  'Approved',
  'In Production',
  'Ready To Ship',
  'Delivered',
  'Cancelled'
];

const STATUS_MAP: any = {
  'Pending': { color: 'bg-amber-50 text-amber-600', icon: Clock },
  'Reviewing Design': { color: 'bg-sky-50 text-sky-600', icon: Eye },
  'Approved': { color: 'bg-emerald-50 text-emerald-600', icon: CheckCircle2 },
  'In Production': { color: 'bg-indigo-50 text-indigo-600', icon: Package },
  'Delivered': { color: 'bg-slate-50 text-slate-600', icon: CheckCircle2 },
  'Cancelled': { color: 'bg-rose-50 text-rose-600', icon: AlertCircle },
};

export default function CustomizedOrdersAdminPage() {
  const db = useFirestore();
  const { toast } = useToast();
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedOrder, setSelectedOrder] = useState<any>(null);
  
  const ordersQuery = useMemo(() => {
    if (!db) return null;
    return query(collection(db, 'customized_orders'), orderBy('createdAt', 'desc'));
  }, [db]);
  
  const { data: orders, loading } = useCollection<any>(ordersQuery);

  const filteredOrders = orders?.filter((o: any) => 
    o.customerName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    o.productName?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleUpdateStatus = async (orderId: string, newStatus: string) => {
    if (!db) return;
    try {
      await updateDoc(doc(db, 'customized_orders', orderId), { status: newStatus });
      toast({ title: "Status Updated", description: `Order is now ${newStatus}` });
      setSelectedOrder(null);
    } catch (err) {
      toast({ variant: "destructive", title: "Error", description: "Failed to update status." });
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-1">
          <h1 className="text-3xl font-headline font-black text-slate-800 uppercase tracking-tight flex items-center gap-3">
            <Wand2 className="h-8 w-8 text-sky-600" /> Customized AI Orders
          </h1>
          <p className="text-sm text-slate-400 font-medium italic">Manage unique creations generated by your customers.</p>
        </div>
      </div>

      <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-50 overflow-hidden">
        <div className="p-8 border-b border-slate-50 flex items-center gap-4">
           <div className="relative flex-1 max-w-md">
             <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-300" />
             <Input 
               value={searchTerm}
               onChange={(e) => setSearchTerm(e.target.value)}
               placeholder="Search by customer or product..." 
               className="pl-11 h-12 rounded-xl border-slate-100 focus-visible:ring-sky-500 bg-slate-50/50" 
             />
           </div>
        </div>

        {loading ? (
          <div className="py-32 flex justify-center">
            <Loader2 className="h-8 w-8 animate-spin text-sky-500" />
          </div>
        ) : filteredOrders && filteredOrders.length > 0 ? (
          <Table>
            <TableHeader>
              <TableRow className="border-none bg-slate-50/50">
                <TableHead className="px-8 font-black text-[10px] uppercase tracking-widest text-slate-400 h-14">Customer</TableHead>
                <TableHead className="font-black text-[10px] uppercase tracking-widest text-slate-400 h-14">Product Canvas</TableHead>
                <TableHead className="font-black text-[10px] uppercase tracking-widest text-slate-400 h-14">AI Design</TableHead>
                <TableHead className="font-black text-[10px] uppercase tracking-widest text-slate-400 h-14">Status</TableHead>
                <TableHead className="px-8 text-right h-14"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredOrders.map((order: any) => {
                const status = STATUS_MAP[order.status] || STATUS_MAP['Pending'];
                return (
                  <TableRow key={order.id} className="hover:bg-slate-50/30 transition-colors border-slate-50 group">
                    <TableCell className="px-8">
                       <div className="font-black text-sm text-slate-800">{order.customerName}</div>
                       <div className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">{order.customerEmail}</div>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-3">
                         <div className="relative w-10 h-10 rounded-lg overflow-hidden bg-slate-50 border shrink-0">
                            <Image src={order.originalProductImage} alt="Base" fill className="object-cover" unoptimized />
                         </div>
                         <div className="font-black text-xs text-slate-700">{order.productName}</div>
                      </div>
                    </TableCell>
                    <TableCell>
                       <button 
                        onClick={() => setSelectedOrder(order)}
                        className="relative w-14 h-14 rounded-xl overflow-hidden bg-slate-50 border ring-2 ring-sky-100 hover:scale-110 transition-transform shadow-lg"
                       >
                         <Image src={order.generatedDesignImage} alt="Design" fill className="object-cover" unoptimized />
                         <div className="absolute inset-0 bg-black/10 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                            <Eye className="h-4 w-4 text-white" />
                         </div>
                       </button>
                    </TableCell>
                    <TableCell>
                      <div className={cn(
                        "inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[10px] font-black uppercase tracking-tight",
                        status.color
                      )}>
                        <status.icon className="h-3 w-3" />
                        {order.status || 'Pending'}
                      </div>
                    </TableCell>
                    <TableCell className="px-8 text-right">
                      <Button variant="ghost" size="icon" onClick={() => setSelectedOrder(order)} className="rounded-xl text-slate-300 hover:text-sky-600 hover:bg-sky-50">
                        <ChevronRight className="h-5 w-5" />
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        ) : (
          <div className="py-32 text-center space-y-4">
             <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mx-auto text-slate-200">
                <Wand2 className="h-8 w-8" />
             </div>
             <p className="text-sm font-bold text-slate-400 uppercase tracking-widest">No customized orders found.</p>
          </div>
        )}
      </div>

      {/* Order Details Modal */}
      <Dialog open={!!selectedOrder} onOpenChange={() => setSelectedOrder(null)}>
        <DialogContent className="max-w-4xl p-0 overflow-hidden rounded-[3rem] border-none shadow-2xl bg-white">
           {selectedOrder && (
             <div className="flex flex-col max-h-[90vh]">
               <DialogHeader className="p-8 border-b bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                       <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center text-sky-600 shadow-sm border">
                          <Package className="h-6 w-6" />
                       </div>
                       <div>
                          <DialogTitle className="text-xl font-headline font-black text-slate-800 uppercase tracking-tight">Custom Request</DialogTitle>
                          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">ID: {selectedOrder.id?.slice(-8).toUpperCase()}</p>
                       </div>
                    </div>
                    <div className={cn("px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest border", STATUS_MAP[selectedOrder.status]?.color)}>
                       {selectedOrder.status}
                    </div>
                  </div>
               </DialogHeader>

               <div className="p-8 overflow-y-auto space-y-10 scrollbar-hide">
                  <div className="grid md:grid-cols-2 gap-10">
                     {/* Visual Section */}
                     <div className="space-y-6">
                        <div className="space-y-3">
                           <Label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-1">AI GENERATED DESIGN</Label>
                           <div className="relative aspect-square rounded-[2.5rem] overflow-hidden border-4 border-sky-100 shadow-2xl bg-slate-50">
                              <Image src={selectedOrder.generatedDesignImage} alt="AI Design" fill className="object-cover" unoptimized />
                              <a 
                                href={selectedOrder.generatedDesignImage} 
                                download 
                                className="absolute bottom-4 right-4 bg-white/90 backdrop-blur-md p-3 rounded-2xl text-sky-600 shadow-lg hover:scale-110 active:scale-95 transition-all"
                              >
                                <Download className="h-5 w-5" />
                              </a>
                           </div>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                           <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                              <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1">Canvas Product</p>
                              <p className="text-xs font-black text-slate-700 truncate">{selectedOrder.productName}</p>
                           </div>
                           <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                              <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1">Total Value</p>
                              <p className="text-xs font-black text-emerald-600">₹{selectedOrder.price?.toLocaleString()}</p>
                           </div>
                        </div>
                     </div>

                     {/* Info Section */}
                     <div className="space-y-8">
                        <div className="space-y-4">
                           <h4 className="text-xs font-black uppercase tracking-widest text-slate-400">CUSTOMER REQUIREMENTS</h4>
                           <div className="bg-slate-50 rounded-3xl p-6 border border-slate-100 space-y-6">
                              <div>
                                 <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">The Prompt</p>
                                 <p className="text-sm font-medium italic text-slate-600 leading-relaxed">"{selectedOrder.customPrompt}"</p>
                              </div>
                              <div className="grid grid-cols-2 gap-4">
                                 <div>
                                    <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-0.5">Name Used</p>
                                    <p className="text-xs font-black text-sky-600 uppercase">{selectedOrder.customizationName || 'N/A'}</p>
                                 </div>
                                 <div>
                                    <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-0.5">Occasion</p>
                                    <p className="text-xs font-black text-rose-500 uppercase">{selectedOrder.occasion || 'General'}</p>
                                 </div>
                              </div>
                              {selectedOrder.specialInstructions && (
                                <div>
                                   <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Special Notes</p>
                                   <p className="text-xs font-bold text-slate-500">{selectedOrder.specialInstructions}</p>
                                </div>
                              )}
                           </div>
                        </div>

                        <div className="space-y-4">
                           <h4 className="text-xs font-black uppercase tracking-widest text-slate-400">ACTION PANEL</h4>
                           <div className="grid gap-3">
                              <div className="relative">
                                 <select 
                                   onChange={(e) => handleUpdateStatus(selectedOrder.id, e.target.value)}
                                   className="w-full h-14 rounded-2xl border-2 border-slate-100 px-4 text-sm font-black uppercase tracking-widest outline-none bg-white focus:border-sky-500"
                                   value={selectedOrder.status}
                                 >
                                    {STATUS_OPTIONS.map(s => <option key={s} value={s}>{s.toUpperCase()}</option>)}
                                 </select>
                              </div>
                              <Button className="w-full h-14 rounded-2xl bg-slate-900 text-white font-black uppercase text-[10px] tracking-[0.2em] gap-2">
                                <MessageSquare className="h-4 w-4" /> Contact via WhatsApp
                              </Button>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
             </div>
           )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
